### ISSUE TITLE
need help! running gazebo simulation on groovy

### ISSUE THREAD

**Issue by dikke** [turtlebot/turtlebot_simulator#11]
Hello 

I am trying to run the launch the turtlebot on gazebo (Gazebo multi-robot simulator, version 1.5.0) by running:

```
   roslaunch turtlebot_gazebo turtlebot_empty_world.launch
```

and I got the following error message :

   Error [parser.cc:712] XML Element[sensor:contact], child of element[link] not defined in      SDF. Ignoring.[link]
Error [parser.cc:703] Error reading element <link>
Error [parser.cc:703] Error reading element <model>
Error [parser.cc:369] Unable to read element <sdf>
Error [parser.cc:319] parse as old urdf model file failed.
Error [World.cc:1440] Unable to read sdf string[<!--

any idea?

Thank you

**Comment by stonier** [comment]
We're not working on this any longer for groovy - waiting for hydro to push out with some updates that should make the last few things work that the gazebo team couldn't commit time for (given their schedule with the darpa challenge).

I'd recommend waiting for that.

**Comment by bit-pirate** [comment]
https://github.com/turtlebot/turtlebot_simulator/issues/9

**Comment by dikke** [comment]
thank you very much for your reply.The reason I am using turtlbot_simulator is because I want to see how the navigation stack works on the other robot. And then apply the similar things to my own robot. I have tried erractics, robintino, turtlebot simulator, but they all outdated and no longer support. Do you know any simulator (gazebo) that is updated and supported ? Thanks!

**Comment by bit-pirate** [comment]
@dikke the turtlebot simulator will be ready soon. Stay tuned to issue #9 to follow up on the progress.
I'll close this issue for now. For general questions about simulators, I recommend using ROS Answers (http://answers.ros.org/). If you have turtlebot_simulator-related questions, please publish them on the mentioned issue.
