### ISSUE TITLE
Models for playground are not loading

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_simulator#17]
Mentioned here: http://answers.gazebosim.org/question/4399/turtlebot_gazebo-world-not-loading-models/
And already ticketed for Kobuki simulation here: https://github.com/yujinrobot/kobuki_desktop/issues/21

**Comment by bit-pirate** [comment]
Following up here: https://bitbucket.org/osrf/gazebo/issue/806/gzclient-does-not-download-missing-models

**Comment by jihoonl** [comment]
Playground is loading well now. Also referenced issue has been resolved.
