### ISSUE TITLE
Stage uses it's own move base launchers and params

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_simulator#21]
I would prefer if we could use the actual turtlebot's launchers so we make sure we immediately simulate what we are actually using (this is intuitive - takes a while of digging around to realise that we aren't) as well as helping to make sure that our parameters/configuration is in sync (again, this is intuitive - I didn't expect to find a different configuration).

**Comment by stonier** [comment]
Definitely shouldn't have experimental ces waiterbot configuration in here.

**Comment by stonier** [comment]
The pull request above redirects everything back to the real turtlebot configuration. If folk want to experiment, _that_ should be the starting place (it's too hard to maintain copies in sync). They can then fork/branch/create their own launchers for their own experimentation.

**Comment by jihoonl** [comment]
both indigo and hydro-devel in turtlebot_simulator uses turtlebot_navigation configuration from now on.
