### ISSUE TITLE
Ros Indigo Turtlebot Gazebo Simulator -- Failed to load models and publish /camera/* and /odom/ topics

### ISSUE THREAD

**Issue by tm507211** [turtlebot/turtlebot_simulator#23]
I know that the turtlebot packages for ROS Indigo are not yet supported/finished but I hope reporting this issue can help you find and fix the issue.

When launching the turtlebot gazebo simulator using

roslaunch turtlebot_gazebo turtlebot empty_world.launch

A segfault occurs, (I believe in the gzserver), and the gazebo-2 process dies.

The gazebo client window will remain open however none of the models are visible and while I can click on the models and place them in the gazebo window, they disappear as soon as I place them. The models list in the gzclient shows that no models are in the window.

Also running rostopic echo on any of the topics that do show in the rostopic list, reveal that none of the data is being published.

While I was able to run gdb on the nodes launched in the turtlebot_empty_world.launch file, I could not find the error and I am unsure how to run gdb on the entire launch sequence or individually on the gzserver or gzclient.

The reason I believe the segfault is occuring within gzserver process is because I have tried running the turtlebot simulator by opening three terminal windows and running the following commands:

roscore
rosrun gazebo_ros gzserver
roslaunch turtlebot_gazebo turtlebot_empty_world.launch

and the segfault error message will occur in the
rosrun gazebo_ros gzserver's terminal window.

Both methods of running the turtlebot simulator give the same results.
Method one: using just the roslaunch command
Method two: using the three commands listed above.

A full output of the command can be found on my post on ROS Answers.
http://answers.ros.org/question/174374/ros-indigo-turtlebot-gazebo-simulation/

**Comment by mikeferguson** [comment]
This is almost certainly due to https://github.com/ros/rosdistro/issues/4633 since the turtlebot would be using a URDF.

**Comment by jihoonl** [comment]
I wonder if this issue is still valid.

**Comment by jihoonl** [comment]
Please reopen this if it is still a problem.
