### ISSUE TITLE
Problems starting amcl_demo

### ISSUE THREAD

**Issue by schultza** [turtlebot/turtlebot_simulator#33]
Hey,

since some time I am not able to let the amcl demo run.
I am just starting the program with following command:
roslaunch turtlebot_gazebo amcl_demo.launch map_file:=/home/schultza/my_map.yaml

my_map was created some time before.

Here is the output:

... logging to /home/schultza/.ros/log/c1a96b00-4495-11e4-b4f1-485ab604aada/roslaunch-Andreas-1030.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Andreas:40742/
# SUMMARY

PARAMETERS
- /amcl/base_frame_id: base_footprint
- /amcl/gui_publish_rate: 10.0
- /amcl/initial_pose_a: 0.0
- /amcl/initial_pose_x: 0.0
- /amcl/initial_pose_y: 0.0
- /amcl/kld_err: 0.05
- /amcl/kld_z: 0.99
- /amcl/laser_lambda_short: 0.1
- /amcl/laser_likelihood_max_dist: 2.0
- /amcl/laser_max_beams: 60
- /amcl/laser_max_range: 12.0
- /amcl/laser_model_type: likelihood_field
- /amcl/laser_sigma_hit: 0.2
- /amcl/laser_z_hit: 0.5
- /amcl/laser_z_max: 0.05
- /amcl/laser_z_rand: 0.5
- /amcl/laser_z_short: 0.05
- /amcl/max_particles: 2000
- /amcl/min_particles: 500
- /amcl/odom_alpha1: 0.2
- /amcl/odom_alpha2: 0.2
- /amcl/odom_alpha3: 0.2
- /amcl/odom_alpha4: 0.2
- /amcl/odom_alpha5: 0.1
- /amcl/odom_frame_id: odom
- /amcl/odom_model_type: diff
- /amcl/recovery_alpha_fast: 0.0
- /amcl/recovery_alpha_slow: 0.0
- /amcl/resample_interval: 1
- /amcl/transform_tolerance: 1.0
- /amcl/update_min_a: 0.2
- /amcl/update_min_d: 0.25
- /amcl/use_map_topic: False
- /move_base/TrajectoryPlannerROS/acc_lim_theta: 1.0
- /move_base/TrajectoryPlannerROS/acc_lim_x: 0.5
- /move_base/TrajectoryPlannerROS/acc_lim_y: 0.0
- /move_base/TrajectoryPlannerROS/dwa: True
- /move_base/TrajectoryPlannerROS/gdist_scale: 0.8
- /move_base/TrajectoryPlannerROS/heading_lookahead: 0.325
- /move_base/TrajectoryPlannerROS/holonomic_robot: False
- /move_base/TrajectoryPlannerROS/max_vel_theta: 1.0
- /move_base/TrajectoryPlannerROS/max_vel_x: 0.3
- /move_base/TrajectoryPlannerROS/max_vel_y: 0.0
- /move_base/TrajectoryPlannerROS/meter_scoring: True
- /move_base/TrajectoryPlannerROS/min_in_place_vel_theta: 0.6
- /move_base/TrajectoryPlannerROS/min_vel_theta: -1.0
- /move_base/TrajectoryPlannerROS/min_vel_x: 0.1
- /move_base/TrajectoryPlannerROS/min_vel_y: 0.0
- /move_base/TrajectoryPlannerROS/occdist_scale: 0.01
- /move_base/TrajectoryPlannerROS/oscillation_reset_dist: 0.05
- /move_base/TrajectoryPlannerROS/pdist_scale: 0.6
- /move_base/TrajectoryPlannerROS/sim_time: 3.0
- /move_base/TrajectoryPlannerROS/vtheta_samples: 20
- /move_base/TrajectoryPlannerROS/vx_samples: 6
- /move_base/TrajectoryPlannerROS/vy_samples: 0
- /move_base/TrajectoryPlannerROS/xy_goal_tolerance: 0.15
- /move_base/TrajectoryPlannerROS/yaw_goal_tolerance: 0.3
- /move_base/controller_frequency: 5.0
- /move_base/controller_patience: 3.0
- /move_base/global_costmap/bump/clearing: False
- /move_base/global_costmap/bump/data_type: PointCloud2
- /move_base/global_costmap/bump/marking: True
- /move_base/global_costmap/bump/max_obstacle_height: 0.15
- /move_base/global_costmap/bump/min_obstacle_height: 0.0
- /move_base/global_costmap/bump/topic: mobile_base/senso...
- /move_base/global_costmap/global_frame: /map
- /move_base/global_costmap/inflation_radius: 0.5
- /move_base/global_costmap/map_type: voxel
- /move_base/global_costmap/max_obstacle_height: 0.6
- /move_base/global_costmap/observation_sources: scan bump
- /move_base/global_costmap/obstacle_range: 2.5
- /move_base/global_costmap/origin_z: 0.0
- /move_base/global_costmap/publish_frequency: 0.5
- /move_base/global_costmap/publish_voxel_map: False
- /move_base/global_costmap/raytrace_range: 3.0
- /move_base/global_costmap/robot_base_frame: /base_footprint
- /move_base/global_costmap/robot_radius: 0.18
- /move_base/global_costmap/scan/clearing: True
- /move_base/global_costmap/scan/data_type: LaserScan
- /move_base/global_costmap/scan/marking: True
- /move_base/global_costmap/scan/max_obstacle_height: 0.35
- /move_base/global_costmap/scan/min_obstacle_height: 0.25
- /move_base/global_costmap/scan/topic: scan
- /move_base/global_costmap/static_map: True
- /move_base/global_costmap/transform_tolerance: 0.5
- /move_base/global_costmap/update_frequency: 1.0
- /move_base/global_costmap/z_resolution: 0.2
- /move_base/global_costmap/z_voxels: 2
- /move_base/local_costmap/bump/clearing: False
- /move_base/local_costmap/bump/data_type: PointCloud2
- /move_base/local_costmap/bump/marking: True
- /move_base/local_costmap/bump/max_obstacle_height: 0.15
- /move_base/local_costmap/bump/min_obstacle_height: 0.0
- /move_base/local_costmap/bump/topic: mobile_base/senso...
- /move_base/local_costmap/global_frame: /map
- /move_base/local_costmap/height: 4.0
- /move_base/local_costmap/inflation_radius: 0.5
- /move_base/local_costmap/map_type: voxel
- /move_base/local_costmap/max_obstacle_height: 0.6
- /move_base/local_costmap/observation_sources: scan bump
- /move_base/local_costmap/obstacle_range: 2.5
- /move_base/local_costmap/origin_z: 0.0
- /move_base/local_costmap/publish_frequency: 2.0
- /move_base/local_costmap/publish_voxel_map: False
- /move_base/local_costmap/raytrace_range: 3.0
- /move_base/local_costmap/resolution: 0.05
- /move_base/local_costmap/robot_base_frame: /base_footprint
- /move_base/local_costmap/robot_radius: 0.18
- /move_base/local_costmap/rolling_window: True
- /move_base/local_costmap/scan/clearing: True
- /move_base/local_costmap/scan/data_type: LaserScan
- /move_base/local_costmap/scan/marking: True
- /move_base/local_costmap/scan/max_obstacle_height: 0.35
- /move_base/local_costmap/scan/min_obstacle_height: 0.25
- /move_base/local_costmap/scan/topic: scan
- /move_base/local_costmap/static_map: False
- /move_base/local_costmap/transform_tolerance: 0.5
- /move_base/local_costmap/update_frequency: 5.0
- /move_base/local_costmap/width: 4.0
- /move_base/local_costmap/z_resolution: 0.2
- /move_base/local_costmap/z_voxels: 2
- /move_base/oscillation_distance: 0.2
- /move_base/oscillation_timeout: 10.0
- /move_base/planner_frequency: 1.0
- /move_base/planner_patience: 5.0
- /move_base/shutdown_costmaps: False
- /navigation_velocity_smoother/accel_lim_v: 0.6
- /navigation_velocity_smoother/accel_lim_w: 5.4
- /navigation_velocity_smoother/decel_factor: 1.0
- /navigation_velocity_smoother/frequency: 20.0
- /navigation_velocity_smoother/robot_feedback: 2
- /navigation_velocity_smoother/speed_lim_v: 0.8
- /navigation_velocity_smoother/speed_lim_w: 5.4
- /rosdistro: indigo
- /rosversion: 1.11.9

NODES
  /
    amcl (amcl/amcl)
    kobuki_safety_controller (nodelet/nodelet)
    map_server (map_server/map_server)
    move_base (move_base/move_base)
    navigation_velocity_smoother (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[map_server-1]: started with pid [1051]
process[amcl-2]: started with pid [1052]
process[navigation_velocity_smoother-3]: started with pid [1053]
process[kobuki_safety_controller-4]: started with pid [1054]
ERROR: cannot launch node of type [move_base/move_base]: can't locate node [move_base] in package [move_base]
amcl: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char _) &((av)->bins[((1) - 1) \* 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
[amcl-2] process has died [pid 1052, exit code -6, cmd /home/schultza/catkin_ws/devel/lib/amcl/amcl scan:=scan __name:=amcl __log:=/home/schultza/.ros/log/c1a96b00-4495-11e4-b4f1-485ab604aada/amcl-2.log].
log file: /home/schultza/.ros/log/c1a96b00-4495-11e4-b4f1-485ab604aada/amcl-2_.log
^C[kobuki_safety_controller-4] killing on exit
[navigation_velocity_smoother-3] killing on exit
[map_server-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

See that move_base and amcl are creating problems.

**Comment by jihoonl** [comment]
I have tested amcl_demo in indigo, and worked fine without any error. Also hydro release has not been touched for a while. 

Can you post more information like how you installed and how you started? a log with `--screen` flag would be helpful too.

Also It seems like the system cannot find `move_base`. Did you install `move_base` package?

**Comment by schultza** [comment]
First thanks for your answer:

Here is the output with `--screen` flag:

schultza@Andreas:~$ roslaunch turtlebot_gazebo amcl_demo.launch map_file:=/home/schultza/my_map.yaml --screen
... logging to /home/schultza/.ros/log/5181c7de-454c-11e4-9ad3-485ab604aada/roslaunch-Andreas-3724.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Andreas:48655/

# SUMMARY

PARAMETERS
- /amcl/base_frame_id: base_footprint
- /amcl/gui_publish_rate: 10.0
- /amcl/initial_pose_a: 0.0
- /amcl/initial_pose_x: 0.0
- /amcl/initial_pose_y: 0.0
- /amcl/kld_err: 0.05
- /amcl/kld_z: 0.99
- /amcl/laser_lambda_short: 0.1
- /amcl/laser_likelihood_max_dist: 2.0
- /amcl/laser_max_beams: 60
- /amcl/laser_max_range: 12.0
- /amcl/laser_model_type: likelihood_field
- /amcl/laser_sigma_hit: 0.2
- /amcl/laser_z_hit: 0.5
- /amcl/laser_z_max: 0.05
- /amcl/laser_z_rand: 0.5
- /amcl/laser_z_short: 0.05
- /amcl/max_particles: 2000
- /amcl/min_particles: 500
- /amcl/odom_alpha1: 0.2
- /amcl/odom_alpha2: 0.2
- /amcl/odom_alpha3: 0.2
- /amcl/odom_alpha4: 0.2
- /amcl/odom_alpha5: 0.1
- /amcl/odom_frame_id: odom
- /amcl/odom_model_type: diff
- /amcl/recovery_alpha_fast: 0.0
- /amcl/recovery_alpha_slow: 0.0
- /amcl/resample_interval: 1
- /amcl/transform_tolerance: 1.0
- /amcl/update_min_a: 0.2
- /amcl/update_min_d: 0.25
- /amcl/use_map_topic: False
- /move_base/TrajectoryPlannerROS/acc_lim_theta: 1.0
- /move_base/TrajectoryPlannerROS/acc_lim_x: 0.5
- /move_base/TrajectoryPlannerROS/acc_lim_y: 0.0
- /move_base/TrajectoryPlannerROS/dwa: True
- /move_base/TrajectoryPlannerROS/gdist_scale: 0.8
- /move_base/TrajectoryPlannerROS/heading_lookahead: 0.325
- /move_base/TrajectoryPlannerROS/holonomic_robot: False
- /move_base/TrajectoryPlannerROS/max_vel_theta: 1.0
- /move_base/TrajectoryPlannerROS/max_vel_x: 0.3
- /move_base/TrajectoryPlannerROS/max_vel_y: 0.0
- /move_base/TrajectoryPlannerROS/meter_scoring: True
- /move_base/TrajectoryPlannerROS/min_in_place_vel_theta: 0.6
- /move_base/TrajectoryPlannerROS/min_vel_theta: -1.0
- /move_base/TrajectoryPlannerROS/min_vel_x: 0.1
- /move_base/TrajectoryPlannerROS/min_vel_y: 0.0
- /move_base/TrajectoryPlannerROS/occdist_scale: 0.01
- /move_base/TrajectoryPlannerROS/oscillation_reset_dist: 0.05
- /move_base/TrajectoryPlannerROS/pdist_scale: 0.6
- /move_base/TrajectoryPlannerROS/sim_time: 3.0
- /move_base/TrajectoryPlannerROS/vtheta_samples: 20
- /move_base/TrajectoryPlannerROS/vx_samples: 6
- /move_base/TrajectoryPlannerROS/vy_samples: 0
- /move_base/TrajectoryPlannerROS/xy_goal_tolerance: 0.15
- /move_base/TrajectoryPlannerROS/yaw_goal_tolerance: 0.3
- /move_base/controller_frequency: 5.0
- /move_base/controller_patience: 3.0
- /move_base/global_costmap/bump/clearing: False
- /move_base/global_costmap/bump/data_type: PointCloud2
- /move_base/global_costmap/bump/marking: True
- /move_base/global_costmap/bump/max_obstacle_height: 0.15
- /move_base/global_costmap/bump/min_obstacle_height: 0.0
- /move_base/global_costmap/bump/topic: mobile_base/senso...
- /move_base/global_costmap/global_frame: /map
- /move_base/global_costmap/inflation_radius: 0.5
- /move_base/global_costmap/map_type: voxel
- /move_base/global_costmap/max_obstacle_height: 0.6
- /move_base/global_costmap/observation_sources: scan bump
- /move_base/global_costmap/obstacle_range: 2.5
- /move_base/global_costmap/origin_z: 0.0
- /move_base/global_costmap/publish_frequency: 0.5
- /move_base/global_costmap/publish_voxel_map: False
- /move_base/global_costmap/raytrace_range: 3.0
- /move_base/global_costmap/robot_base_frame: /base_footprint
- /move_base/global_costmap/robot_radius: 0.18
- /move_base/global_costmap/scan/clearing: True
- /move_base/global_costmap/scan/data_type: LaserScan
- /move_base/global_costmap/scan/marking: True
- /move_base/global_costmap/scan/max_obstacle_height: 0.35
- /move_base/global_costmap/scan/min_obstacle_height: 0.25
- /move_base/global_costmap/scan/topic: scan
- /move_base/global_costmap/static_map: True
- /move_base/global_costmap/transform_tolerance: 0.5
- /move_base/global_costmap/update_frequency: 1.0
- /move_base/global_costmap/z_resolution: 0.2
- /move_base/global_costmap/z_voxels: 2
- /move_base/local_costmap/bump/clearing: False
- /move_base/local_costmap/bump/data_type: PointCloud2
- /move_base/local_costmap/bump/marking: True
- /move_base/local_costmap/bump/max_obstacle_height: 0.15
- /move_base/local_costmap/bump/min_obstacle_height: 0.0
- /move_base/local_costmap/bump/topic: mobile_base/senso...
- /move_base/local_costmap/global_frame: /map
- /move_base/local_costmap/height: 4.0
- /move_base/local_costmap/inflation_radius: 0.5
- /move_base/local_costmap/map_type: voxel
- /move_base/local_costmap/max_obstacle_height: 0.6
- /move_base/local_costmap/observation_sources: scan bump
- /move_base/local_costmap/obstacle_range: 2.5
- /move_base/local_costmap/origin_z: 0.0
- /move_base/local_costmap/publish_frequency: 2.0
- /move_base/local_costmap/publish_voxel_map: False
- /move_base/local_costmap/raytrace_range: 3.0
- /move_base/local_costmap/resolution: 0.05
- /move_base/local_costmap/robot_base_frame: /base_footprint
- /move_base/local_costmap/robot_radius: 0.18
- /move_base/local_costmap/rolling_window: True
- /move_base/local_costmap/scan/clearing: True
- /move_base/local_costmap/scan/data_type: LaserScan
- /move_base/local_costmap/scan/marking: True
- /move_base/local_costmap/scan/max_obstacle_height: 0.35
- /move_base/local_costmap/scan/min_obstacle_height: 0.25
- /move_base/local_costmap/scan/topic: scan
- /move_base/local_costmap/static_map: False
- /move_base/local_costmap/transform_tolerance: 0.5
- /move_base/local_costmap/update_frequency: 5.0
- /move_base/local_costmap/width: 4.0
- /move_base/local_costmap/z_resolution: 0.2
- /move_base/local_costmap/z_voxels: 2
- /move_base/oscillation_distance: 0.2
- /move_base/oscillation_timeout: 10.0
- /move_base/planner_frequency: 1.0
- /move_base/planner_patience: 5.0
- /move_base/shutdown_costmaps: False
- /navigation_velocity_smoother/accel_lim_v: 0.6
- /navigation_velocity_smoother/accel_lim_w: 5.4
- /navigation_velocity_smoother/decel_factor: 1.0
- /navigation_velocity_smoother/frequency: 20.0
- /navigation_velocity_smoother/robot_feedback: 2
- /navigation_velocity_smoother/speed_lim_v: 0.8
- /navigation_velocity_smoother/speed_lim_w: 5.4
- /rosdistro: indigo
- /rosversion: 1.11.9

NODES
  /
    amcl (amcl/amcl)
    kobuki_safety_controller (nodelet/nodelet)
    map_server (map_server/map_server)
    move_base (move_base/move_base)
    navigation_velocity_smoother (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[map_server-1]: started with pid [3742]
[ INFO] [1411715691.739144172]: Loading map from image "/home/schultza/my_map.pgm"
[ INFO] [1411715691.746268572]: Read a 512 X 512 map @ 0.050 m/cell
process[amcl-2]: started with pid [3763]
**\* Error in `/home/schultza/catkin_ws/devel/lib/amcl/amcl': corrupted double-linked list: 0x09290950 ***
process[navigation_velocity_smoother-3]: started with pid [3860]
[ INFO] [1411715691.977665338]: Loading nodelet /navigation_velocity_smoother of type yocs_velocity_smoother/VelocitySmootherNodelet to manager /mobile_base_nodelet_manager with the following remappings:
[ INFO] [1411715691.977775063]: /navigation_velocity_smoother/odometry -> /odom
[ INFO] [1411715691.977909361]: /navigation_velocity_smoother/robot_cmd_vel -> /mobile_base/commands/velocity
[ INFO] [1411715691.977978660]: /navigation_velocity_smoother/smooth_cmd_vel -> /cmd_vel_mux/input/navi
process[kobuki_safety_controller-4]: started with pid [3942]
[amcl-2] process has died [pid 3763, exit code -6, cmd /home/schultza/catkin_ws/devel/lib/amcl/amcl scan:=scan __name:=amcl __log:=/home/schultza/.ros/log/5181c7de-454c-11e4-9ad3-485ab604aada/amcl-2.log].
log file: /home/schultza/.ros/log/5181c7de-454c-11e4-9ad3-485ab604aada/amcl-2*.log
[ INFO] [1411715692.139738430]: Loading nodelet /kobuki_safety_controller of type kobuki_safety_controller/SafetyControllerNodelet to manager /mobile_base_nodelet_manager with the following remappings:
[ INFO] [1411715692.140121959]: /kobuki_safety_controller/cmd_vel -> /cmd_vel_mux/input/safety_controller
[ INFO] [1411715692.140221783]: /kobuki_safety_controller/events/bumper -> /mobile_base/events/bumper
[ INFO] [1411715692.140296581]: /kobuki_safety_controller/events/cliff -> /mobile_base/events/cliff
[ INFO] [1411715692.140433731]: /kobuki_safety_controller/events/wheel_drop -> /mobile_base/events/wheel_drop
ERROR: cannot launch node of type [move_base/move_base]: can't locate node [move_base] in package [move_base]
^C[kobuki_safety_controller-4] killing on exit
[map_server-1] killing on exit
[navigation_velocity_smoother-3] killing on exit
[ INFO] [1411715706.572873131, 206.050000000]: Unloading nodelet /kobuki_safety_controller from manager /mobile_base_nodelet_manager
[ INFO] [1411715706.573311371, 206.050000000]: Unloading nodelet /navigation_velocity_smoother from manager /mobile_base_nodelet_manager
shutting down processing monitor...
... shutting down processing monitor complete
done
schultza@Andreas:~$ sudo apt-get install ros-indigo-move-base
[sudo] password for schultza: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
ros-indigo-move-base is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

You can also see that it says that i already got the newest version of move_base.

To the installation:
1. ROS Installation with `sudo apt-get install ros-indigo-desktop-full`
2. Gazebo Installation with `sudo apt-get install ros-indigo-gazebo-ros-pkgs-current`
3. Gazebo_ros Installtion with `sudo apt-get install ros-indigo-gazebo-ros-pkgs ros-indigo-gazebo-ros-control`
4. Download turtlebot_simulator from github with `git clone https://github.com/turtlebot/turtlebot_simulator.git`
5. Install Dependencies with `rosdep install --from-paths src -y -i`
6. Install turtlebot_apps with `git clone https://github.com/turtlebot/turtlebot_apps.git`
7. `catkin_make`

Then see above commands, I stareted befor playground launch

thanks

**Comment by jihoonl** [comment]
Hm..this is weird. It seems like configuration issue rather than turtlebot_simulator code problem. Could you ask on ROS Answers? I think you can get better answer there.

**Comment by schultza** [comment]
Hm, i got the problem. I accidently installed the hydro branch of turtlebot stuff. So my bad. I am sorry and thanks for your time. You can close or better delete :)
