### ISSUE TITLE
Resetting Gazebo Simulation Problem

### ISSUE THREAD

**Issue by marjinal1st** [turtlebot/turtlebot_simulator#48]
I'm using ROS Indigo on Ubuntu 14.04.

Whenever I reset the simulation on Gazebo (Edit - Reset World), all the movement stops and I've to relaunch the simulation on **turtlebot_gazebo** package again.

Is there a way to reset the simulation properly without relaunching it?

**Comment by tfoote** [comment]
When you reset the world, time jumps backwards. Some algorithms/implementations are not robust to that. Or they may abort behaviors if those time jumps are detected.

I cannot reproduce the issue using keyboard_teleop. The vehicle does get reset back to the origin with zero speed, but can be driven immediately afterwards. I'm going to close as I can't reproduce the issue.
