### ISSUE TITLE
Turtlebot Gazebo simulation in Groovy

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_simulator#5]
For this to work, Kobuki & Create simulations need to be working. Work on these can can be tracked here:
Kobuki: https://github.com/yujinrobot/kobuki_desktop/issues/8
Create: ?

Turtlebot-specific issue will be posted here.

Current issues:
- <del>Kinect simulation (Kinect's ROS Gazebo plugin) crashes. Ticket files for Gazebo:</del>
  - <del>https://bitbucket.org/osrf/gazebo/issue/557/camera-sensor-segfaults-on-loading</del>

**Comment by stonier** [comment]
Tully mentioned that he would chase up John Tsu(?) to see if he can kickstart us in the right direction.

**Comment by bit-pirate** [comment]
John Hsu. :-)

**Comment by bit-pirate** [comment]
New Kinect/3d sensor plugin is working fine now.

Kobuki simulation issues TODO.

**Comment by bit-pirate** [comment]
We are not supporting TurtleBot simulation in Groovy. Issue #9 tracks the progress for the Hydro release.
