### ISSUE TITLE
turtlebot_in_stage.launch robot description incompatible: kobuki_description vs stage_ros

### ISSUE THREAD

**Issue by MichaelKorn** [turtlebot/turtlebot_simulator#53]
Hello,
there is an issue with this tutorial: http://wiki.ros.org/turtlebot_stage/Tutorials/indigo/Bring%20up%20TurtleBot%20in%20stage

The height of the robot base is jumping all the time. This is aggravating due to the camera in rviz is fixed to the robot base by default.
This happens because [stage_ros sends the identity transformation between base_footprint an base_link](https://github.com/ros-simulation/stage_ros/blob/master/src/stageros.cpp#L490).
In [kobuki_description base_link has a hight of 0.0102m](https://github.com/yujinrobot/kobuki_description/blob/master/urdf/kobuki.urdf.xacro#L31).

**Comment by jihoonl** [comment]
This is also related to [Change in robot state publisher](https://github.com/ros/robot_state_publisher/pull/39). This PR has changed the default value use_tf_static = False.
