### ISSUE TITLE
Release into kinetic

### ISSUE THREAD

**Issue by 130s** [turtlebot/turtlebot_simulator#55]
I'm sure it's in someone's todo list, and sorry if it's already WIP, but I open a ticket just because I didn't see it on [buildfarm's status page](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=turtlebot).

**Comment by stonier** [comment]
I've got to get kobuki desktop fixed and released.  But coming very soon.

**Comment by ghost** [comment]
Thanks @stonier for working on this.  Looking forward to it!

**Comment by spragunr** [comment]
Thanks @stonier for this and for all of your work supporting Turtlebot. Is there an ETA for releasing turtlebot_simulator for kinetic?  I'm teaching a course in the fall and need to decide whether the lab can be updated to kinetic.  This seems to be the last missing piece.

**Comment by tfoote** [comment]
https://github.com/ros/rosdistro/pull/12387
