### ISSUE TITLE
Turtlebot spinning in place + not going straight

### ISSUE THREAD

**Issue by nzlz** [turtlebot/turtlebot_simulator#57]
Hello, 
As I show in the videos above, the Turtlebot is spins around itself a bit, which could affect the direction when I try to go straight. When the real time factor (simulation speed) is normal the robot makes an acceptable straight line, but when the simulation is set to maximum the robot clearly turns to the right. This strange behaviour does not happen in empty worlds, just when the robot is inside a model. Any possible solution to this issue?

Nestor

---

Video1 - Spining around itself
https://www.youtube.com/watch?v=LdImDUFFOck&feature=youtu.be

Video 2 - Trying to go straight -  in 0:40 normal speed is tested
https://www.youtube.com/watch?v=ltf0eb4ZMcE&feature=youtu.be

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

When you re-ask please note that your youtube videos are private and unviewable.
