### ISSUE TITLE
How to add moving obstacles to "turtlebot_stage"

### ISSUE THREAD

**Issue by airjohnson** [turtlebot/turtlebot_simulator#59]
Hi,
    I'm trying to add moving obstacles to the "turtlebot_stage". According to the tutorial (http://wiki.ros.org/turtlebot_stage/Tutorials/indigo/Customizing%20the%20Stage%20Simulator), moveable objects can be added to the map.
     I tried to add velocity definition to the "myBlock.inc" and "maze.world" files, and I also referred to the  model file definition (http://wiki.ros.org/turtlebot_stage/Tutorials/indigo/Customizing%20the%20Stage%20Simulator). But the obstacle only moves when it is dragged by the mouse. It doesn't move by itself.
    Is it possible to add moving obstacles to the "turtlebot_stage"?
    If so, what should I do?
    I really appreciate your help. Thanks a lot!

**Comment by tfoote** [comment]
Please ask questions on https://answers.ros.org we try to answer questions there and reserve the issue tracker for bugs and development discussions.
