### ISSUE TITLE
turtlebot present gazebo launch doesn't compatible gazebo6. will crush when launch.

### ISSUE THREAD

**Issue by asimay** [turtlebot/turtlebot_simulator#63]
turtlebot present gazebo(version 2.3) launch doesn't compatible gazebo6. will crush when launch.
I update my gazebo version, and find turtlebot gazebo cannot be used....

**Comment by tfoote** [comment]
If you update your gazebo version, you will need to recompile all the gazebo plugins against that version of gazebo, and possibly update the API. 

There are tutorials for running different versions of gazebo with ROS packages here: http://gazebosim.org/tutorials/?tut=ros_wrapper_versions
