### ISSUE TITLE
how to add noise to the camera model?

### ISSUE THREAD

**Issue by onlytailei** [turtlebot/turtlebot_simulator#66]
Can we do it like in the gazebo sdf file?
http://gazebosim.org/tutorials?tut=sensor_noise#Cameranoise

**Comment by tfoote** [comment]
Yes, the turtlebot simulator is a gazebo instance. You need to modify the turtlebot_description https://github.com/turtlebot/turtlebot/blob/kinetic/turtlebot_description/urdf/turtlebot_gazebo.urdf.xacro#L9

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
