### ISSUE TITLE
IMU data has huge covariance

### ISSUE THREAD

**Issue by ulassbin** [turtlebot/turtlebot_simulator#69]
Hello I am currently trying to fuse some sensors with IMU on the turtlebot to improve the readings. However I have noticed that the IMU has huge covariances in orientation and angular_velocity field( As shown below).  Is there a way to fix this?
Thanks.
![image](https://user-images.githubusercontent.com/38883137/47252705-c22d7a80-d451-11e8-977a-20274c0edcdc.png)

**Comment by tfoote** [comment]
Can you please be more specific about what you'd like to see it changed to? Also what version of the simulation are you running with what versions of the turtlebot? And what launch files would be helpful.

As a side note we also ask that you copy and pasted console text as text and not screenshot it. Text output from the screenshot cannot be searched or copy and pasted.

**Comment by ulassbin** [comment]
Thanks for the quick reply. I have just started coding in ROS so thanks for the tips as well. So my ROS distribution is kinetic. I am launching the simulation as "roslaunch turtlebot_gazebo turtlebot_world.launch". I am not sure about the version but the file named "turtlebot_gazeboConfig-version.cmake" has this line in it "set(PACKAGE_VERSION "2.2.3")" so the version might be 2.2.3 . I don't know how covariance is computed for IMU's but I think it should be lower than 1 million for me to fuse the data.

If there is a way to setup covariances of the imu with say URDF files, I can probably adjust it with accuracy-resolution of the imu that I am planning to use.

**Comment by tfoote** [comment]
You should be able to adjust the covariance. However I'll note that I believe that those covariances are set very high to indicate that they're effectively not being measured. And that you should only rely on the Z rotation information. On the TB1 we only had a 1 axis gyro which this is likely set for.

**Comment by ulassbin** [comment]
Thanks for the feedback.
