### ISSUE TITLE
missing run depends on turtlebot stack for turtlebot_description

### ISSUE THREAD

**Issue by tfoote** [turtlebot/turtlebot_simulator#7]
The launch file calls find turtlebot_description.  

http://answers.ros.org/question/58360/when-launching-simulator-errorinvalid-arg-tag-turtlebot_description/

**Comment by bit-pirate** [comment]
Sorry for the spam! Was training myself to isolate specific commits using branch, commit, reset, delete branch, branch, commit and so on ... :-)
The pull request should do the trick.
